### PR TITLE
Add KMeans benchmark to cuML benchmark notebook (and clean results)

### PR DESCRIPTION
**Pull request by JohnZed**
The KMeans benchmark is trivial and follows the pattern of the others. I also purged all output as it was previously broken.

### CODE REVIEW

**Comment by JohnZed** [comment]
@cjnolet could you take a look when you get a chance?

**Comment by JohnZed** [comment]
> The changes for adding the kmeans benchmark look great.
> 
> I suggest we also add the `n_jobs = -1` option to the constructors of all the models, even if it's ignored by some of the underlying algorithms. That way users are seeing as fair a benchmark as possible.

How about if I put a constant near the top somewhere for N_JOBS and use that throughout so it's easy for the user to choose? I can default to -1 with a comment explaining.

**Comment by cjnolet** [comment]
That sounds like a great idea.

**Comment by taureandyernv** [comment]
Where are we on this.  I see a change requested, but not sure if the change was made :)

**Comment by JohnZed** [comment]
@cjnolet and @taureandyernv - here are the changes discussed above. Sorry about the delay - had a couple of system issues.

**Pull request merged**
