### PR TITLE
Update Dockerfile notebook paths

### LINKED ISSUE #71: Dockerfile paths don't match notebook directories
The top-level Dockerfile has some old paths, failing the `make build` command:

```diff
# these don't exist
- ADD cpu_comparisons /rapids/notebooks/extended/cpu_comparisons
- ADD tutorials /rapids/notebooks/extended/tutorials
- ADD cugraph_benchmark /rapids/notebooks/extended/cugraph_benchmark
# but these do
+ ADD beginner /rapids/notebooks/extended/beginner
+ ADD advanced /rapids/notebooks/extended/advanced
+ ADD expert /rapids/notebooks/extended/expert
```

### PR DESCRIPTION
**Pull request by trxcllnt**
Closes #71

### CODE REVIEW

**Comment by taureandyernv** [comment]
hey @trxcllnt !  Thanks for making the issue and providing the changes.  We just made further changes to the repo structure, so i put the new template fixes as a suggestion.  Can you commit and I'll merge?  Thanks for all your help!!

**Comment by paulhendricks** [comment]
The easiest fix here is to change the old Dockerfile (found here: https://github.com/rapidsai/notebooks-extended/blob/master/Dockerfile) to this new format:

```Dockerfile
FROM rapidsai/rapidsai:cuda9.2-runtime-ubuntu16.04

SHELL ["/bin/bash", "-c"]
RUN source activate rapids && conda install -y \
        matplotlib \
        scikit-learn \
        seaborn \
        python-louvain \
        jinja2 \
        && pip install graphistry mockito

RUN source activate rapids && conda install -c \
        nvidia/label/cuda10.0 -c rapidsai/label/cuda10.0 -c numba -c conda-forge -c defaults cugraph

RUN apt update &&\
    apt install -y graphviz &&\
    source activate rapids && pip install graphviz
        
# ToDo: let user supply kaggle creds
RUN source activate rapids && pip install kaggle

ADD data /data
RUN mkdir -p /rapids/notebooks/extended
# symlinked so users can browse the data directory inside JupyterLab
RUN ln -s /data /rapids/notebooks/extended

ADD . /data /rapids/notebooks/extended

WORKDIR /rapids/notebooks/extended
CMD source activate rapids && sh /rapids/notebooks/utils/start-jupyter.sh
```

That way, ALL folders and files are added regardless of any new structural changes introduced in the future.

**Comment by paulhendricks** [comment]
The key line of difference is:

```
ADD . /data /rapids/notebooks/extended
```

in case that wasn't clear :)

**Comment by trxcllnt** [comment]
@taureandyernv ok, I've updated the Dockerfile to work with the new notebooks. I also added a `.dockerignore` file, so the `ADD . .` line will pick up any new files. Here's the new contents:
```shellsource
$ docker run --rm -it rapidsai/notebooks-extended:latest sh -c "pwd && ls -All"
/rapids/notebooks/extended
total 36
drwxr-xr-x 3 root root 4096 Jun 21 08:42 advanced_notebooks
drwxr-xr-x 5 root root 4096 Jun 21 08:42 blog_notebooks
drwxr-xr-x 3 root root 4096 Jun 21 08:46 colab_notebooks
drwxr-xr-x 3 root root 4096 Jun 21 08:42 competition_notebooks
drwxr-xr-x 4 root root 4096 Jun 21 08:42 conference_notebooks
lrwxrwxrwx 1 root root    5 Jun 21 08:55 data -> /data
drwxr-xr-x 4 root root 4096 Jun 21 08:42 getting_started_notebooks
drwxr-xr-x 5 root root 4096 Jun 21 08:42 intermediate_notebooks
-rw-r--r-- 1 root root 1231 Jun 13 03:15 multimedia_links.ipynb
drwxr-xr-x 2 root root 4096 Jun 21 08:46 utils
```

**Comment by taureandyernv** [comment]
Thanks so much @trxcllnt !!!  Great job!

**Pull request merged**
